### ISSUE TITLE
Mauvais "parsage"

### ISSUE THREAD

**Issue by MrManchot** [NTag/suivicolissimo#1]
Bonjour,

Je me permet de vous contacter, l'API ne fonctionne pas dans certain cas. Par exemple:
http://api.ntag.fr/colissimo/?id=6A09114631070 -- http://www.colissimo.fr/portail_colissimo/suivre.do?colispart=6A09114631070

J'ai l'impression que les preg_replace de la méthode getSuivi() ne fonctionne pas correctement a cause du tableau "Adresse et horaires" a l'intérieur du tableau parsé.

J'espère que ces infos vous seront utiles ! :)

Merci en tout cas pour ce super script :)

**Comment by NTag** [comment]
Merci beaucoup, c'était effectivement ce lien "Adresse et horaires" qui bloquait le script. J'ai corrigé via f3c3f56a23a54e9919429e1fc8f0c6811f361405.

**Comment by MrManchot** [comment]
Super merci :)
