### ISSUE TITLE
Possibility to choose Language

### ISSUE THREAD

**Issue by eni23** [NTag/suivicolissimo#2]
Hello

First , thanks a lot for your API, saved me a lot of time and pain.
It would be nice to have a possibilty to choose language of tracking-messages since a lot of recipients do not speak french. 

regards, cyrill

**Comment by NTag** [comment]
Hello,

Thank you! Unfortunately, I get the messages directly from Colissimo
website, and I can't choose the language. Moreover, I do not know all
possible messages, and they change often. I should translate them
everytime, so it wouldn't be very good...

Regards,
Basile

**Comment by eni23** [comment]
Hello

I hacked something together with multilanguage-support: https://gist.github.com/eni23/06c7ada2e19918793227 

you can try a demo here: https://data.e23.ch/colissimo/?id=CP440518032FR&lang=de_DE

regards, cyrill
